POST http://localhost:3001/api/persons
content-type: application/json

{
    "content": "test note",
    "important": true
}

###
POST http://localhost:3001/api/persons
content-type: application/json

{
    "name": "Wafa Anam",
    "number": "403 970 6114"
}

### 
POST https://fullstackopen2024-6lbg.onrender.com/api/persons
content-type: application/json

{
    "name": "Wafa Anam",
    "number": "403 970 6114"
}